### PR TITLE
New components (colors not touched)

### PR DESCRIPTION
**Pull request by XenosG**
@MasterLegend2772 Please, review and merge (without homepage). I didnt touch defaults, so colors might not work with our system

### CODE REVIEW

**Comment by XenosG** [comment]
need split merge to avoid unfinished homepage in main

**Comment by XenosG** [comment]
should be able to simple merge now

**Review by MasterLegend2772 — APPROVED** [review]
Suggestions: Squash Merge

**Comment by MasterLegend2772** [comment]
[Page Designs & Overall Design](https://trello.com/c/RMbE8UHw/1-page-designs-overall-design)

**Pull request merged**
